---
area/go:
  - changed-files:
      - any-glob-to-any-file: "cmd/**/*.go"
      - any-glob-to-any-file: "config/**/*.go"
      - any-glob-to-any-file: "logging/**/*.go"
      - any-glob-to-any-file: "go.mod"
      - any-glob-to-any-file: "go.sum"

area/agents:
  - changed-files:
      - any-glob-to-any-file: "agents/**/*"

area/docs:
  - changed-files:
      - any-glob-to-any-file: "README.md"
      - any-glob-to-any-file: "docs/**/*"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/pre-commit:
  - changed-files:
      - any-glob-to-any-file: .pre-commit-config.yaml
      - any-glob-to-any-file: .hooks/**/*
