// Package tools defines tool handlers and execution helpers for agents.
package tools

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/cowdogmoo/squad/executor"
	"github.com/cowdogmoo/squad/logging"
	"github.com/cowdogmoo/squad/metrics"
	"github.com/cowdogmoo/squad/telemetry"
	"github.com/tmc/langchaingo/llms"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

const MaxToolIterations = 100
const maxToolOutput = 64 * 1024
const maxSameToolRepeat = 10
const maxMutatingToolRepeat = 50

const maxReadBytes = 48 * 1024
const maxSearchResults = 200
const contextTokenThreshold = 50_000
const keepRecentMessages = 10
const maxToolResultBytes = 32 * 1024

var defaultSkipDirs = map[string]bool{
	".venv":         true,
	"venv":          true,
	"__pycache__":   true,
	".tox":          true,
	"node_modules":  true,
	".git":          true,
	".mypy_cache":   true,
	".pytest_cache": true,
	".ruff_cache":   true,
	".eggs":         true,
	"target":        true,
	"build":         true,
	"dist":          true,
	"vendor":        true,
}

type editsKeyType struct{}
type editDeadlineKeyType struct{}
type editEnforcerKeyType struct{}

// mutatingTools are tools that legitimately chain in long sequences.
var mutatingTools = map[string]bool{
	"Edit":      true,
	"MultiEdit": true,
	"Write":     true,
}

// maxReadToolRepeat caps consecutive identical Read/Glob/Grep calls.
// Models sometimes re-read the same file despite cache hints; a hard cap
// forces them to move on.
const maxReadToolRepeat = 5

var highRepeatTools = map[string]bool{
	"Read": true,
	"Glob": true,
	"Grep": true,
}

// reInlineModifierGroup matches inline modifier groups like (?n), (?x),
// (?imn), etc. — any (?<letters>) or (?<letters>-<letters>) pattern.
var reInlineModifierGroup = regexp.MustCompile(`\(\?[a-zA-Z]+(?:-[a-zA-Z]+)?\)`)

// sanitizeRegex strips regex syntax that is unsupported by Go's RE2 engine
// but commonly generated by LLMs (e.g., .NET's (?n) explicit-capture flag,
// PCRE's (?x), etc.). RE2 supports (?i), (?m), (?s), (?U) and combinations.
func sanitizeRegex(pattern string) string {
	return reInlineModifierGroup.ReplaceAllStringFunc(pattern, func(match string) string {
		// Extract the flags portion: strip leading "(?" and trailing ")"
		inner := match[2 : len(match)-1]
		// Check each character — keep the group only if ALL flags are valid RE2 flags
		for _, c := range inner {
			if c != 'i' && c != 'm' && c != 's' && c != 'U' && c != '-' {
				return "" // contains unsupported flag, strip entire group
			}
		}
		return match // all flags valid, keep as-is
	})
}

func InitEdits(ctx context.Context) context.Context {
	b := false
	return context.WithValue(ctx, editsKeyType{}, &b)
}

func ResetEditsApplied(ctx context.Context) {
	if b, ok := ctx.Value(editsKeyType{}).(*bool); ok {
		*b = false
	}
}

func MarkEditsApplied(ctx context.Context) {
	if b, ok := ctx.Value(editsKeyType{}).(*bool); ok {
		*b = true
	}
}

func EditsApplied(ctx context.Context) bool {
	if b, ok := ctx.Value(editsKeyType{}).(*bool); ok {
		return *b
	}
	return false
}

// InitEditDeadline sets up the edit deadline tracking on the context.
func InitEditDeadline(ctx context.Context) context.Context {
	b := false
	return context.WithValue(ctx, editDeadlineKeyType{}, &b)
}

// MarkEditDeadlineReached records that the edit deadline was hit.
func MarkEditDeadlineReached(ctx context.Context) {
	if b, ok := ctx.Value(editDeadlineKeyType{}).(*bool); ok {
		*b = true
	}
}

// EditDeadlineReached returns true if the edit deadline stopped the loop.
func EditDeadlineReached(ctx context.Context) bool {
	if b, ok := ctx.Value(editDeadlineKeyType{}).(*bool); ok {
		return *b
	}
	return false
}

type Handler struct {
	Def  llms.Tool
	Call func(ctx context.Context, rawArgs []byte) (string, error)
}

type RepeatTracker struct {
	lastSignature string
	LastName      string
	Count         int
}

func (t *RepeatTracker) Update(calls []llms.ToolCall) {
	signature := ""
	name := ""
	if len(calls) == 1 && calls[0].FunctionCall != nil {
		name = calls[0].FunctionCall.Name
		signature = name + ":" + calls[0].FunctionCall.Arguments
	}
	if signature != "" && signature == t.lastSignature {
		t.Count++
	} else {
		t.Count = 1
		t.lastSignature = signature
		t.LastName = name
	}
}

func (t *RepeatTracker) Exceeded() bool {
	limit := maxSameToolRepeat
	if highRepeatTools[t.LastName] {
		limit = maxReadToolRepeat
	}
	if mutatingTools[t.LastName] {
		limit = maxMutatingToolRepeat
	}
	return t.Count >= limit
}

// EditEnforcer tracks whether an agent has called Edit within a deadline.
// When the deadline is reached without any Edit calls, it signals the loop
// to stop — preventing agents from endlessly reading without producing edits.
type EditEnforcer struct {
	Deadline      int
	editSeen      bool
	readOnlyIters int
}

// NewEditEnforcer creates an enforcer that triggers after deadline iterations
// with no Edit call. Returns nil if deadline <= 0 (disabled).
// When maxIterations is provided (first optional arg), the effective deadline
// is scaled up to at least 30% of maxIterations so that agents with large
// iteration budgets aren't killed before they finish reading.
func NewEditEnforcer(deadline int, maxIterations ...int) *EditEnforcer {
	if deadline <= 0 {
		return nil
	}
	effective := deadline
	if len(maxIterations) > 0 && maxIterations[0] > 0 {
		floor := maxIterations[0] * 3 / 10 // 30% of max iterations
		if floor > effective {
			effective = floor
		}
	}
	return &EditEnforcer{Deadline: effective}
}

// PreEdit reports whether the agent has not yet made any edits.
// It is nil-safe: a nil enforcer is treated as pre-edit.
func (e *EditEnforcer) PreEdit() bool {
	return e == nil || !e.editSeen
}

// ShouldBlockReads returns true when the agent is close to its edit
// deadline and has made no edits.  Reads are blocked starting 2
// iterations before the deadline, giving the model a final chance to
// switch to Edit/Write.  This avoids blocking reads too early — review
// agents need many iterations to read files before editing.
func (e *EditEnforcer) ShouldBlockReads() bool {
	if e == nil || e.editSeen {
		return false
	}
	// Block reads only in the final 2 iterations before the deadline.
	threshold := e.Deadline - 2
	if threshold < 2 {
		threshold = 2
	}
	return e.readOnlyIters >= threshold
}

// SetEditEnforcer stores the enforcer on the context so tool handlers can query it.
func SetEditEnforcer(ctx context.Context, e *EditEnforcer) context.Context {
	return context.WithValue(ctx, editEnforcerKeyType{}, e)
}

// GetEditEnforcer retrieves the enforcer from the context.
func GetEditEnforcer(ctx context.Context) *EditEnforcer {
	if e, ok := ctx.Value(editEnforcerKeyType{}).(*EditEnforcer); ok {
		return e
	}
	return nil
}

// CheckNames inspects tool call names and returns true if the loop should stop.
func (e *EditEnforcer) CheckNames(names []string) bool {
	if e == nil || e.editSeen {
		return false
	}
	for _, name := range names {
		if name == "Edit" || name == "MultiEdit" || name == "Write" {
			e.editSeen = true
			return false
		}
	}
	e.readOnlyIters++
	return e.readOnlyIters >= e.Deadline
}

func RunWithTools(ctx context.Context, llm llms.Model, systemPrompt, userPrompt, workingDir string, maxIterations, editDeadline int, taskCfg *TaskConfig, m *metrics.Metrics, ex executor.Executor, callOpts ...llms.CallOption) (string, error) {
	ctx, span := telemetry.Tracer().Start(ctx, "tool.loop",
		trace.WithAttributes(
			attribute.Int("squad.tool_loop.max_iterations", maxIterations),
		),
	)
	defer span.End()

	// Initialize efficiency features on context.
	ctx = InitReadCache(ctx)
	ctx = InitIterationCounter(ctx)
	ctx = InitTokenCalibration(ctx)
	ctx = InitFileTracker(ctx)
	ctx = InitBgCommandRegistry(ctx)

	handlers, toolDefs := BuildHandlers(workingDir, taskCfg, ex)
	callOpts = append(callOpts, llms.WithTools(toolDefs))

	if maxIterations <= 0 {
		maxIterations = MaxToolIterations
	}

	messages := buildInitialMessages(systemPrompt, userPrompt)
	lastContent, messages, loopErr, done := toolLoop(ctx, llm, messages, handlers, maxIterations, editDeadline, m, callOpts)
	if done {
		return lastContent, nil
	}
	if loopErr != nil && !errors.Is(loopErr, metrics.ErrBudgetExceeded) &&
		!errors.Is(loopErr, ErrIterationLimitReached) &&
		!errors.Is(loopErr, ErrLoopDetected) &&
		!errors.Is(loopErr, ErrEditDeadlineReached) {
		span.RecordError(loopErr)
		span.SetStatus(codes.Error, loopErr.Error())
		return lastContent, loopErr
	}

	return finishToolLoop(ctx, llm, messages, lastContent, maxIterations, m, callOpts)
}

// logIterationStart logs the current iteration number with cost/token info if metrics are available.
func logIterationStart(ctx context.Context, i, maxIter int, m *metrics.Metrics) {
	if m != nil {
		logging.InfoContext(ctx, "model iteration %d/%d (cost=$%.4f, tokens=%d/%d)",
			i+1, maxIter, m.TotalCostWithChildren(), m.InputTokens(), m.OutputTokens())
	} else {
		logging.InfoContext(ctx, "model iteration %d/%d", i+1, maxIter)
	}
}

// checkEditDeadline returns true if the edit deadline has been reached and the loop should stop.
func checkEditDeadline(ctx context.Context, enforcer *EditEnforcer, toolCalls []llms.ToolCall) bool {
	if enforcer == nil {
		return false
	}
	var toolNames []string
	for _, tc := range toolCalls {
		if tc.FunctionCall != nil {
			toolNames = append(toolNames, tc.FunctionCall.Name)
		}
	}
	if enforcer.CheckNames(toolNames) {
		logging.InfoContext(ctx, "edit deadline reached: %d iterations with no Edit calls, stopping tool loop", enforcer.Deadline)
		MarkEditDeadlineReached(ctx)
		return true
	}
	return false
}

// budgetWarningThresholds defines the cost-budget percentages at which a
// warning message is injected into the conversation so the agent can
// prioritise wrapping up.
var budgetWarningThresholds = []float64{0.25, 0.50, 0.75}

// defaultPhaseNudgeIters is the number of read-only iterations before
// injecting a progress-check message.
const defaultPhaseNudgeIters = 3

// extractToolNames collects tool names from tool calls.
func extractToolNames(calls []llms.ToolCall) []string {
	names := make([]string, 0, len(calls))
	for _, tc := range calls {
		if tc.FunctionCall != nil {
			names = append(names, tc.FunctionCall.Name)
		}
	}
	return names
}

// injectPhaseNudge checks the phase enforcer and appends a nudge message if needed.
func injectPhaseNudge(ctx context.Context, pe *PhaseEnforcer, toolNames []string, messages []llms.MessageContent, iteration int) []llms.MessageContent {
	nudge := pe.ObserveTools(toolNames)
	if nudge == "" {
		return messages
	}
	logging.InfoContext(ctx, "injecting phase nudge at iteration %d", iteration)
	return append(messages, llms.MessageContent{
		Role:  llms.ChatMessageTypeHuman,
		Parts: []llms.ContentPart{llms.TextPart(nudge)},
	})
}

// injectBudgetWarnings checks budget thresholds and appends warning messages.
func injectBudgetWarnings(ctx context.Context, m *metrics.Metrics, warned []bool, messages []llms.MessageContent) []llms.MessageContent {
	if m == nil || m.MaxCost <= 0 {
		return messages
	}
	pct := m.BudgetUsedPct()
	for idx, threshold := range budgetWarningThresholds {
		if warned[idx] || pct < threshold {
			continue
		}
		warned[idx] = true
		pctInt := int(threshold * 100)
		remaining := m.RemainingBudget()
		msg := budgetWarningMessage(pctInt, remaining)
		logging.InfoContext(ctx, "injecting budget warning at %d%% (remaining=$%.4f)", pctInt, remaining)
		messages = append(messages, llms.MessageContent{
			Role:  llms.ChatMessageTypeHuman,
			Parts: []llms.ContentPart{llms.TextPart(msg)},
		})
	}
	return messages
}

// budgetWarningMessage returns the warning text for a given budget percentage.
func budgetWarningMessage(pctInt int, remaining float64) string {
	if pctInt == 25 {
		return fmt.Sprintf(ProgressCheckPrompt, remaining)
	}
	return fmt.Sprintf(
		"[BUDGET WARNING] You have used %d%% of your cost budget ($%.2f remaining). "+
			"Prioritise completing your current work and producing output. "+
			"Do not start reading new files — finish what you have and wrap up.",
		pctInt, remaining)
}

func toolLoop(ctx context.Context, llm llms.Model, messages []llms.MessageContent, handlers map[string]Handler, maxIter, editDeadline int, m *metrics.Metrics, callOpts []llms.CallOption) (string, []llms.MessageContent, error, bool) {
	var lastContent string
	var repeat RepeatTracker
	var loopDetector LoopDetector
	editEnforcer := NewEditEnforcer(editDeadline, maxIter)
	if editEnforcer != nil {
		ctx = SetEditEnforcer(ctx, editEnforcer)
	}
	phaseEnforcer := NewPhaseEnforcer(defaultPhaseNudgeIters)
	if phaseEnforcer != nil {
		ctx = SetPhaseEnforcer(ctx, phaseEnforcer)
	}
	budgetWarned := make([]bool, len(budgetWarningThresholds))
	for i := 0; i < maxIter; i++ {
		SetIteration(ctx, i)
		logIterationStart(ctx, i, maxIter, m)
		iterStart := time.Now()
		response, err := retryGenerateContent(ctx, llm, messages, callOpts)
		iterDuration := time.Since(iterStart)
		if err != nil {
			logging.InfoContext(ctx, "model call failed in %s: %v", iterDuration.Round(time.Millisecond), err)
			return lastContent, messages, fmt.Errorf("GenerateContent failed: %w", err), false
		}
		if isEmptyResponse(response) {
			logging.InfoContext(ctx, "model returned empty response in %s", iterDuration.Round(time.Millisecond))
			return lastContent, messages, fmt.Errorf("model returned empty response"), false
		}

		if m != nil {
			m.IncrementIterations()
		}

		mergedContent, mergedToolCalls := mergeChoices(ctx, response.Choices, m)
		if mergedContent != "" {
			lastContent = mergedContent
		}
		if len(mergedToolCalls) == 0 {
			logging.InfoContext(ctx, "model returned final response in %s (no tool calls)", iterDuration.Round(time.Millisecond))
			return mergedContent, messages, nil, true
		}
		if mergedContent != "" {
			logging.InfoContext(ctx, "model: %s", TruncateString(strings.ReplaceAll(mergedContent, "\n", " "), 200))
		}
		logging.InfoContext(ctx, "model making %d tool call(s) in %s", len(mergedToolCalls), iterDuration.Round(time.Millisecond))

		repeat.Update(mergedToolCalls)
		if repeat.Exceeded() {
			logging.InfoContext(ctx, "model called %s %d times in a row, breaking tool loop", repeat.LastName, repeat.Count)
			break
		}

		if checkEditDeadline(ctx, editEnforcer, mergedToolCalls) {
			return lastContent, messages, ErrEditDeadlineReached, false
		}

		messages = appendToolCallMessage(messages, mergedContent, mergedToolCalls, ctx)
		messages = executeToolCalls(ctx, messages, mergedToolCalls, handlers)

		// Feed tool results into loop detector.
		loopDetector.Record(mergedToolCalls, extractToolResults(messages))
		if loopDetector.Stuck() {
			logging.InfoContext(ctx, "loop detected: agent repeating identical tool calls with same results, stopping")
			return lastContent, messages, ErrLoopDetected, false
		}

		if m != nil && m.BudgetExceeded() {
			logging.InfoContext(ctx, "budget exceeded ($%.4f >= $%.4f max), stopping tool loop", m.TotalCostWithChildren(), m.MaxCost)
			return lastContent, messages, metrics.ErrBudgetExceeded, false
		}

		toolNames := extractToolNames(mergedToolCalls)
		messages = injectPhaseNudge(ctx, phaseEnforcer, toolNames, messages, i)
		messages = injectBudgetWarnings(ctx, m, budgetWarned, messages)
		messages = compactMessages(ctx, messages)
	}
	return lastContent, messages, ErrIterationLimitReached, false
}

// isEmptyResponse reports whether the model returned no usable content.
func isEmptyResponse(resp *llms.ContentResponse) bool {
	return resp == nil || len(resp.Choices) == 0
}

// extractToolResults pulls tool call IDs and their result content from the
// last message in the conversation (which should be the tool-result message).
func extractToolResults(messages []llms.MessageContent) map[string]string {
	results := make(map[string]string)
	if len(messages) == 0 {
		return results
	}
	last := messages[len(messages)-1]
	for _, part := range last.Parts {
		if tcr, ok := part.(llms.ToolCallResponse); ok {
			results[tcr.ToolCallID] = tcr.Content
		}
	}
	return results
}

func extractTokenUsage(gi map[string]any, m *metrics.Metrics, ctx ...context.Context) {
	if m == nil {
		return
	}
	inputKeys := []string{"PromptTokens", "prompt_tokens", "InputTokens", "input_tokens"}
	outputKeys := []string{"CompletionTokens", "completion_tokens", "OutputTokens", "output_tokens"}

	input := extractTokenValue(gi, inputKeys)
	output := extractTokenValue(gi, outputKeys)

	if input > 0 || output > 0 {
		m.AddTokens(input, output)
	}

	// Feed actual input token count into calibration if context is available.
	if input > 0 && len(ctx) > 0 {
		if tc := GetTokenCalibration(ctx[0]); tc != nil {
			// We don't have the exact estimated count here, but we record
			// it so the overall ratio can be calibrated from total counts.
			tc.Record(int(input), int(input)) // self-calibrating baseline
		}
	}
}

// mergeChoices collects text and tool calls across all response choices.
// Anthropic returns separate content blocks (text, tool_use) as separate
// Choices; we must collect tool calls across all of them.
func mergeChoices(ctx context.Context, choices []*llms.ContentChoice, m *metrics.Metrics) (string, []llms.ToolCall) {
	var content string
	var toolCalls []llms.ToolCall
	for _, ch := range choices {
		if gi := ch.GenerationInfo; gi != nil {
			logging.DebugContext(ctx, "generation info: %v", gi)
			if m != nil {
				extractTokenUsage(gi, m, ctx)
			}
		}
		if ch.Content != "" {
			content = ch.Content
		}
		toolCalls = append(toolCalls, ch.ToolCalls...)
	}
	return content, toolCalls
}

func extractTokenValue(gi map[string]any, keys []string) int64 {
	for _, key := range keys {
		if v, ok := gi[key]; ok {
			if val := toInt64(v); val > 0 {
				return val
			}
		}
	}
	return 0
}

func toInt64(v any) int64 {
	switch t := v.(type) {
	case int:
		return int64(t)
	case int64:
		return t
	case float64:
		return int64(t)
	default:
		return 0
	}
}

func finishToolLoop(ctx context.Context, llm llms.Model, messages []llms.MessageContent, lastContent string, maxIter int, m *metrics.Metrics, callOpts []llms.CallOption) (string, error) {
	budgetExceeded := m != nil && m.BudgetExceeded()

	if budgetExceeded {
		logging.InfoContext(ctx, "budget exceeded - making final summary call with tool_choice=none")
		messages = append(messages, llms.MessageContent{
			Role:  llms.ChatMessageTypeHuman,
			Parts: []llms.ContentPart{llms.TextPart("Your cost budget has been exhausted. Produce your final structured output now. Do NOT request any tool calls.")},
		})
	} else {
		logging.InfoContext(ctx, "tool loop ended after %d iterations, requesting final response with tool_choice=none", maxIter)
		// Inject a message telling the model to produce its final output.
		// Without this, the model often returns empty content because it was
		// planning to continue working.
		messages = append(messages, llms.MessageContent{
			Role:  llms.ChatMessageTypeHuman,
			Parts: []llms.ContentPart{llms.TextPart("You have reached the maximum number of tool-calling iterations. Produce your final structured output now based on all the data you have collected. Do NOT request any tool calls.")},
		})
	}

	finalOpts := make([]llms.CallOption, len(callOpts), len(callOpts)+1)
	copy(finalOpts, callOpts)
	finalOpts = append(finalOpts, llms.WithToolChoice("none"))

	response, err := retryGenerateContent(ctx, llm, messages, finalOpts)
	if err == nil && response != nil && len(response.Choices) > 0 {
		if m != nil {
			m.IncrementIterations()
			if gi := response.Choices[0].GenerationInfo; gi != nil {
				extractTokenUsage(gi, m, ctx)
			}
		}
		if response.Choices[0].Content != "" {
			logging.InfoContext(ctx, "final call produced response (%d bytes)", len(response.Choices[0].Content))
			if budgetExceeded {
				return response.Choices[0].Content, metrics.ErrBudgetExceeded
			}
			return response.Choices[0].Content, nil
		}
	} else if budgetExceeded {
		// Grace call failed; fall back to whatever we had.
		logging.InfoContext(ctx, "budget-exceeded grace call failed (err=%v), falling back to last content", err)
		if lastContent != "" {
			return lastContent, metrics.ErrBudgetExceeded
		}
		return "", metrics.ErrBudgetExceeded
	}

	if lastContent != "" {
		logging.InfoContext(ctx, "returning last partial content (%d bytes)", len(lastContent))
		if budgetExceeded {
			return lastContent, metrics.ErrBudgetExceeded
		}
		return lastContent, nil
	}

	if budgetExceeded {
		return "", metrics.ErrBudgetExceeded
	}
	return "", fmt.Errorf("tool loop ended after %d iterations with no usable response", maxIter)
}

func buildInitialMessages(systemPrompt, userPrompt string) []llms.MessageContent {
	messages := []llms.MessageContent{}
	if systemPrompt != "" {
		// Mark the system prompt for caching.  Note: langchaingo v0.1.14's
		// Anthropic provider serializes the system field as a plain string
		// and silently drops cache_control.  We set it anyway so it takes
		// effect once upstream is fixed.
		messages = append(messages, llms.MessageContent{
			Role: llms.ChatMessageTypeSystem,
			Parts: []llms.ContentPart{
				llms.WithCacheControl(
					llms.TextPart(systemPrompt),
					&llms.CacheControl{Type: "ephemeral"},
				),
			},
		})
	}
	// Wrap the user prompt with cache_control as well.  The Anthropic
	// provider correctly propagates CachedContent on human messages, so
	// this is the path that actually enables prompt caching today.
	messages = append(messages, llms.MessageContent{
		Role: llms.ChatMessageTypeHuman,
		Parts: []llms.ContentPart{
			llms.WithCacheControl(
				llms.TextPart(userPrompt),
				&llms.CacheControl{Type: "ephemeral"},
			),
		},
	})
	return messages
}

func appendToolCallMessage(messages []llms.MessageContent, textContent string, toolCalls []llms.ToolCall, ctx context.Context) []llms.MessageContent {
	toolNames := make([]string, 0, len(toolCalls))
	// Tool calls MUST come first in the parts list.  The langchaingo Anthropic
	// provider's handleAIMessage only inspects Parts[0] to decide the message
	// type; if Parts[0] is TextContent it creates a text-only assistant message
	// and drops all tool_use blocks, causing a tool_use_id mismatch error on
	// the next API call.  Placing tool calls first ensures they are preserved.
	var parts []llms.ContentPart
	for _, toolCall := range toolCalls {
		if toolCall.FunctionCall != nil && toolCall.FunctionCall.Name != "" {
			toolNames = append(toolNames, toolCall.FunctionCall.Name)
		}
		parts = append(parts, llms.ToolCall{
			ID:           toolCall.ID,
			Type:         toolCall.Type,
			FunctionCall: toolCall.FunctionCall,
		})
	}
	if textContent != "" {
		parts = append(parts, llms.TextContent{Text: textContent})
	}
	if len(toolNames) > 0 {
		logging.InfoContext(ctx, "tool calls requested: %s", strings.Join(toolNames, ", "))
	}
	return append(messages, llms.MessageContent{
		Role:  llms.ChatMessageTypeAI,
		Parts: parts,
	})
}

// serialTools are tools that must not run concurrently because they
// mutate shared state (filesystem, executor) in order-dependent ways.
var serialTools = map[string]bool{
	"Bash":           true,
	"BashBackground": true,
	"Edit":           true,
	"MultiEdit":      true,
	"Write":          true,
	"Task":           true,
}

func executeToolCalls(ctx context.Context, messages []llms.MessageContent, toolCalls []llms.ToolCall, handlers map[string]Handler) []llms.MessageContent {
	// Batch all tool results into a single message.  Anthropic requires every
	// tool_result to be in the same user message that follows the assistant
	// message containing the corresponding tool_use blocks.
	parts := make([]llms.ContentPart, len(toolCalls))

	// Determine if we can parallelize: only when there are multiple calls
	// and none of them are serial (state-mutating) tools.
	canParallelize := len(toolCalls) > 1
	if canParallelize {
		for _, tc := range toolCalls {
			if tc.FunctionCall != nil && serialTools[tc.FunctionCall.Name] {
				canParallelize = false
				break
			}
		}
	}

	if canParallelize {
		logging.InfoContext(ctx, "executing %d tool calls in parallel", len(toolCalls))
		var wg sync.WaitGroup
		wg.Add(len(toolCalls))
		for i, toolCall := range toolCalls {
			go func(idx int, tc llms.ToolCall) {
				defer wg.Done()
				parts[idx] = executeToolCall(ctx, tc, handlers)
			}(i, toolCall)
		}
		wg.Wait()
	} else {
		for i, toolCall := range toolCalls {
			parts[i] = executeToolCall(ctx, toolCall, handlers)
		}
	}

	return append(messages, llms.MessageContent{
		Role:  llms.ChatMessageTypeTool,
		Parts: parts,
	})
}

func executeToolCall(ctx context.Context, toolCall llms.ToolCall, handlers map[string]Handler) llms.ToolCallResponse {
	toolResponse := llms.ToolCallResponse{
		ToolCallID: toolCall.ID,
	}
	if toolCall.FunctionCall == nil {
		toolResponse.Content = "tool call missing function definition"
		return toolResponse
	}

	handler, ok := handlers[toolCall.FunctionCall.Name]
	if !ok {
		toolResponse.Content = fmt.Sprintf("unknown tool: %s", toolCall.FunctionCall.Name)
		logging.DebugContext(ctx, "unknown tool requested: %s", toolCall.FunctionCall.Name)
		return toolResponse
	}

	toolName := toolCall.FunctionCall.Name
	ctx, span := telemetry.Tracer().Start(ctx, "tool."+toolName,
		trace.WithAttributes(
			attribute.String("squad.tool.name", toolName),
		),
	)
	defer span.End()

	toolResponse.Name = toolName
	argsSummary := toolArgsSummary(toolName, toolCall.FunctionCall.Arguments)
	logging.InfoContext(ctx, "  → %s %s", toolName, argsSummary)
	logging.DebugContext(ctx, "tool %s full args: %s", toolName, TruncateString(toolCall.FunctionCall.Arguments, 500))
	toolStart := time.Now()
	output, err := handler.Call(ctx, []byte(toolCall.FunctionCall.Arguments))
	toolDuration := time.Since(toolStart)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		// Include both output (e.g., command stdout/stderr) and error message
		if output != "" {
			toolResponse.Content = fmt.Sprintf("%s\n\nerror: %v", output, err)
		} else {
			toolResponse.Content = fmt.Sprintf("error: %v", err)
		}
		logging.InfoContext(ctx, "  ✗ %s failed in %s: %s", toolName, toolDuration.Round(time.Millisecond), TruncateString(err.Error(), 200))
	} else {
		toolResponse.Content = output
		logging.InfoContext(ctx, "  ✓ %s done in %s (%d bytes)", toolName, toolDuration.Round(time.Millisecond), len(output))
	}
	span.SetAttributes(attribute.Int("squad.tool.output_bytes", len(toolResponse.Content)))
	return toolResponse
}

// toolArgsSummary extracts a short, human-readable summary from tool call arguments.
// For Bash it shows the command, for Read/Write/Edit the path, for Grep the pattern, etc.
// argString extracts the first matching string value from a parsed JSON args map.
func argString(args map[string]interface{}, keys ...string) string {
	for _, k := range keys {
		if v, ok := args[k]; ok {
			if s, ok := v.(string); ok {
				return s
			}
		}
	}
	return ""
}

// simpleArgKeys maps tool names to the single arg key that summarizes them.
var simpleArgKeys = map[string]string{
	"Read":      "path",
	"Write":     "path",
	"Edit":      "path",
	"MultiEdit": "path",
	"Glob":      "pattern",
}

func toolArgsSummary(toolName, argsJSON string) string {
	var args map[string]interface{}
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return ""
	}
	if key, ok := simpleArgKeys[toolName]; ok {
		return argString(args, key)
	}
	return toolArgsSummaryComplex(toolName, args)
}

func toolArgsSummaryComplex(toolName string, args map[string]interface{}) string {
	switch toolName {
	case "Bash":
		if cmd := argString(args, "command"); cmd != "" {
			return TruncateString(cmd, 120)
		}
	case "Grep":
		p := argString(args, "pattern")
		if path := argString(args, "path"); path != "" {
			return p + " in " + path
		}
		return p
	case "Task":
		agent := argString(args, "agent")
		prompt := TruncateString(argString(args, "prompt"), 80)
		if agent != "" {
			return fmt.Sprintf("agent=%s prompt=%q", agent, prompt)
		}
	case "TaskResult":
		return "id=" + argString(args, "id")
	}
	return ""
}

func BuildHandlers(workingDir string, taskCfg *TaskConfig, ex executor.Executor) (map[string]Handler, []llms.Tool) {
	handlers := map[string]Handler{}

	add := func(handler Handler) {
		name := handler.Def.Function.Name
		handlers[name] = handler
	}

	add(Handler{Def: definitionRead(), Call: readTool(workingDir)})
	add(Handler{Def: definitionWrite(), Call: trackEdits(writeTool(workingDir))})
	add(Handler{Def: definitionEdit(), Call: trackEdits(editTool(workingDir))})
	add(Handler{Def: definitionGlob(), Call: globTool(workingDir)})
	add(Handler{Def: definitionGrep(), Call: grepTool(workingDir)})
	add(Handler{Def: definitionBash(), Call: bashTool(ex)})
	add(Handler{Def: definitionBashBg(), Call: bashBackgroundTool(ex)})
	add(Handler{Def: definitionBashOutput(), Call: bashOutputTool()})
	add(Handler{Def: definitionMultiEdit(), Call: trackEdits(multiEditTool(workingDir))})
	add(Handler{Def: definitionSystemInfo(), Call: systemInfoTool(ex)})
	add(Handler{Def: definitionRepoMap(), Call: repoMapTool(workingDir)})

	if taskCfg != nil {
		// Only register Task/TaskResult when the agent is allowed to spawn children.
		// DisableTask nils CallModel while keeping taskCfg alive for ExtraTools.
		if taskCfg.CallModel != nil {
			add(Handler{Def: definitionTask(), Call: taskTool(*taskCfg)})
			if taskCfg.Registry != nil {
				add(Handler{Def: definitionTaskResult(), Call: taskResultTool(*taskCfg)})
			}
		}
		if taskCfg.Findings != nil {
			agentName := taskCfg.AgentName
			if agentName == "" {
				agentName = "unknown"
			}
			add(Handler{Def: definitionReportFinding(), Call: reportFindingTool(taskCfg.Findings, agentName)})
		}
		// Merge additional tools from external providers (e.g., MCP servers).
		for _, h := range taskCfg.ExtraTools {
			add(h)
		}
	}

	toolDefs := make([]llms.Tool, 0, len(handlers))
	for _, handler := range handlers {
		toolDefs = append(toolDefs, handler.Def)
	}
	sort.Slice(toolDefs, func(i, j int) bool {
		return toolDefs[i].Function.Name < toolDefs[j].Function.Name
	})

	return handlers, toolDefs
}

func trackEdits(call func(ctx context.Context, rawArgs []byte) (string, error)) func(ctx context.Context, rawArgs []byte) (string, error) {
	return func(ctx context.Context, rawArgs []byte) (string, error) {
		result, err := call(ctx, rawArgs)
		if err == nil {
			MarkEditsApplied(ctx)
		}
		return result, err
	}
}

func definitionRead() llms.Tool {
	return llms.Tool{
		Type: "function",
		Function: &llms.FunctionDefinition{
			Name:        "Read",
			Description: "Read a text file. Large files are automatically truncated (head+tail). Use offset/limit to read specific line ranges of large files.",
			Parameters: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"path":   map[string]any{"type": "string", "description": "Path to the file."},
					"offset": map[string]any{"type": "integer", "description": "Start line (1-based). Omit to start from beginning."},
					"limit":  map[string]any{"type": "integer", "description": "Max lines to return. Omit to read to end."},
				},
				"required": []string{"path"},
			},
		},
	}
}

func definitionWrite() llms.Tool {
	return llms.Tool{
		Type: "function",
		Function: &llms.FunctionDefinition{
			Name:        "Write",
			Description: "Write content to a file, creating directories as needed.",
			Parameters: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"path":    map[string]any{"type": "string", "description": "Path to the file."},
					"content": map[string]any{"type": "string", "description": "File contents."},
				},
				"required": []string{"path", "content"},
			},
		},
	}
}

func definitionEdit() llms.Tool {
	return llms.Tool{
		Type: "function",
		Function: &llms.FunctionDefinition{
			Name:        "Edit",
			Description: "Replace text in a file.",
			Parameters: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"path":        map[string]any{"type": "string", "description": "Path to the file."},
					"old":         map[string]any{"type": "string", "description": "Text to replace."},
					"new":         map[string]any{"type": "string", "description": "Replacement text."},
					"replace_all": map[string]any{"type": "boolean", "description": "Replace all occurrences."},
				},
				"required": []string{"path", "old", "new"},
			},
		},
	}
}

func definitionGlob() llms.Tool {
	return llms.Tool{
		Type: "function",
		Function: &llms.FunctionDefinition{
			Name:        "Glob",
			Description: "Find files matching a glob pattern (supports **).",
			Parameters: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"pattern": map[string]any{"type": "string", "description": "Glob pattern (e.g. **/*.go)."},
				},
				"required": []string{"pattern"},
			},
		},
	}
}

func definitionGrep() llms.Tool {
	return llms.Tool{
		Type: "function",
		Function: &llms.FunctionDefinition{
			Name:        "Grep",
			Description: "Search for a regex pattern in files under a path.",
			Parameters: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"pattern": map[string]any{"type": "string", "description": "Regex pattern to search for."},
					"path":    map[string]any{"type": "string", "description": "File or directory path. Default: ."},
				},
				"required": []string{"pattern"},
			},
		},
	}
}

func definitionBash() llms.Tool {
	return llms.Tool{
		Type: "function",
		Function: &llms.FunctionDefinition{
			Name:        "Bash",
			Description: "Run a shell command in the working directory.",
			Parameters: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"command": map[string]any{"type": "string", "description": "Shell command to run."},
				},
				"required": []string{"command"},
			},
		},
	}
}

// applyFileClassification applies smart truncation and warnings based on file
// size classification. The prefix is prepended to the result (e.g. cache note).
func applyFileClassification(content string, lineCount, dataLen int, prefix string) string {
	classification := ClassifyFileSize(lineCount, dataLen)
	switch classification.Action {
	case "truncate":
		headLines := largeFileLineThreshold * 3 / 4
		tailLines := largeFileLineThreshold / 4
		return prefix + classification.Warning + "\n" + TruncateToLines(content, headLines, tailLines)
	case "warn":
		return prefix + classification.Warning + "\n" + content
	default:
		return prefix + content
	}
}

func readTool(workingDir string) func(ctx context.Context, rawArgs []byte) (string, error) {
	type args struct {
		Path   string `json:"path"`
		Offset int    `json:"offset,omitempty"` // 1-based start line
		Limit  int    `json:"limit,omitempty"`  // max lines
	}
	return func(ctx context.Context, rawArgs []byte) (string, error) {
		var payload args
		if err := json.Unmarshal(rawArgs, &payload); err != nil {
			return "", fmt.Errorf("invalid args: %w", err)
		}

		// Hard-block reads only when the edit deadline is approaching.
		if e := GetEditEnforcer(ctx); e != nil && e.ShouldBlockReads() {
			logging.InfoContext(ctx, "blocking Read call — edit deadline approaching, no edits made yet")
			return "READ BLOCKED — You have already read files. The Read tool is disabled until you call Edit or Write.\n\n" +
				"You are approaching the edit deadline with no edits made. Use the file contents from your " +
				"previous Read calls to construct Edit calls now. Do NOT call Read, Glob, or Grep until you " +
				"have made at least one Edit or Write call.", nil
		}

		path, err := ResolvePath(workingDir, payload.Path)
		if err != nil {
			return "", err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}

		// Record that this file was read (for edit safety checks).
		if ft := GetFileTracker(ctx); ft != nil {
			ft.RecordRead(path)
		}

		// If using offset/limit, skip cache and smart truncation — targeted read.
		if payload.Offset > 0 || payload.Limit > 0 {
			return sliceLines(data, payload.Offset, payload.Limit), nil
		}

		lineCount := strings.Count(string(data), "\n") + 1

		// Check read cache for duplicate reads.
		// Before any edits: return full content with a warning so the model
		// still has data to work from (compaction may have removed the original).
		// After first edit: return a short stub to prevent wasteful re-reads.
		if rc := GetReadCache(ctx); rc != nil {
			hash := HashContent(data)
			if entry, hit := rc.Check(path, hash); hit {
				logReadCacheHit(ctx, payload.Path, entry)
				preEdit := GetEditEnforcer(ctx).PreEdit()
				if preEdit {
					// Return full content with warning — model needs it to write edits.
					// Escalate warning based on how many phase nudges have been ignored.
					var prefix string
					if pe := GetPhaseEnforcer(ctx); pe != nil && pe.NudgesSent() >= 2 {
						prefix = fmt.Sprintf(
							"[WARNING — REPEATED RE-READ #%d. You already read this file at iteration %d. "+
								"Your next tool call MUST be Edit or Write, not Read. "+
								"Here is the content — use it to write tests NOW.]\n",
							pe.NudgesSent(), entry.Iteration)
					} else {
						prefix = fmt.Sprintf(
							"[CACHED — you already read this file at iteration %d. "+
								"STOP re-reading and start writing Edit calls NOW.]\n",
							entry.Iteration)
					}
					return applyFileClassification(string(data), lineCount, len(data), prefix), nil
				}
				return fmt.Sprintf(
					"[CACHED — file unchanged since iteration %d (%d lines, %d bytes). "+
						"You already read this file. Use the contents from your earlier read "+
						"to write Edit calls NOW. Do NOT re-read this file.]",
					entry.Iteration, entry.Lines, entry.Bytes), nil
			}
			rc.Store(path, hash, lineCount, len(data), GetIteration(ctx))
		}

		// Smart truncation for large files.
		if len(data) > maxReadBytes {
			return truncateHeadTail(data), nil
		}

		return applyFileClassification(string(data), lineCount, len(data), ""), nil
	}
}

func sliceLines(data []byte, offset, limit int) string {
	lines := strings.SplitAfter(string(data), "\n")
	totalLines := len(lines)
	// Trim trailing empty element from SplitAfter
	if totalLines > 0 && lines[totalLines-1] == "" {
		lines = lines[:totalLines-1]
		totalLines = len(lines)
	}
	if offset < 1 {
		offset = 1
	}
	start := offset - 1
	if start >= totalLines {
		return fmt.Sprintf("(file has %d lines, offset %d is past end)", totalLines, offset)
	}
	end := totalLines
	if limit > 0 && start+limit < end {
		end = start + limit
	}
	var sb strings.Builder
	fmt.Fprintf(&sb, "[lines %d-%d of %d]\n", offset, end, totalLines)
	for _, line := range lines[start:end] {
		sb.WriteString(line)
	}
	return sb.String()
}

func truncateHeadTail(data []byte) string {
	totalLines := strings.Count(string(data), "\n") + 1
	headSize := maxReadBytes * 3 / 4
	tailSize := maxReadBytes - headSize

	head := string(data[:headSize])
	tail := string(data[len(data)-tailSize:])

	// Find clean line boundaries
	headEnd := strings.LastIndex(head, "\n")
	if headEnd < 0 {
		headEnd = len(head)
	}
	tailStart := strings.Index(tail, "\n")
	if tailStart < 0 {
		tailStart = 0
	} else {
		tailStart++ // skip the newline itself
	}

	headLines := strings.Count(head[:headEnd], "\n") + 1
	tailLines := strings.Count(tail[tailStart:], "\n") + 1
	omitted := totalLines - headLines - tailLines

	return fmt.Sprintf("%s\n\n... [%d lines omitted — file has %d total lines, %d bytes. Use Read with offset/limit for specific sections.] ...\n\n%s",
		head[:headEnd], omitted, totalLines, len(data), tail[tailStart:])
}

func writeTool(workingDir string) func(ctx context.Context, rawArgs []byte) (string, error) {
	type args struct {
		Path    string `json:"path"`
		Content string `json:"content"`
	}
	return func(_ context.Context, rawArgs []byte) (string, error) {
		var payload args
		if err := json.Unmarshal(rawArgs, &payload); err != nil {
			return "", fmt.Errorf("invalid args: %w", err)
		}
		path, err := ResolvePath(workingDir, payload.Path)
		if err != nil {
			return "", err
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return "", err
		}
		if err := os.WriteFile(path, []byte(payload.Content), 0o644); err != nil {
			return "", err
		}
		return fmt.Sprintf("wrote %s (%d bytes)", filepath.ToSlash(payload.Path), len(payload.Content)), nil
	}
}

func editTool(workingDir string) func(ctx context.Context, rawArgs []byte) (string, error) {
	type args struct {
		Path       string   `json:"path"`
		Old        string   `json:"old"`
		New        string   `json:"new"`
		ReplaceAll FlexBool `json:"replace_all"`
	}
	return func(ctx context.Context, rawArgs []byte) (string, error) {
		var payload args
		if err := json.Unmarshal(rawArgs, &payload); err != nil {
			return "", fmt.Errorf("invalid args: %w", err)
		}
		path, err := ResolvePath(workingDir, payload.Path)
		if err != nil {
			return "", err
		}
		if ft := GetFileTracker(ctx); ft != nil {
			if err := ft.ValidateBeforeEdit(path); err != nil {
				return "", err
			}
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}
		content := string(data)
		if !strings.Contains(content, payload.Old) {
			return "", fmt.Errorf("text not found in %s", payload.Path)
		}
		var updated string
		replaced := 1
		if bool(payload.ReplaceAll) {
			replaced = strings.Count(content, payload.Old)
			updated = strings.ReplaceAll(content, payload.Old, payload.New)
		} else {
			updated = strings.Replace(content, payload.Old, payload.New, 1)
		}
		if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
			return "", err
		}
		return fmt.Sprintf("updated %s (%d replacement(s))", filepath.ToSlash(payload.Path), replaced), nil
	}
}

func globTool(workingDir string) func(ctx context.Context, rawArgs []byte) (string, error) {
	type args struct {
		Pattern string `json:"pattern"`
	}
	return func(ctx context.Context, rawArgs []byte) (string, error) {
		// Block glob when the edit deadline is approaching and no edits have been made.
		if e := GetEditEnforcer(ctx); e != nil && e.ShouldBlockReads() {
			logging.InfoContext(ctx, "blocking Glob call — edit deadline approaching, no edits made yet")
			return "GLOB BLOCKED — Edit deadline approaching with no edits. Call Edit or Write first.", nil
		}

		var payload args
		if err := json.Unmarshal(rawArgs, &payload); err != nil {
			return "", fmt.Errorf("invalid args: %w", err)
		}
		pattern := strings.TrimSpace(payload.Pattern)
		if pattern == "" {
			return "", fmt.Errorf("pattern is required")
		}
		matcher, err := newGlobMatcher(pattern)
		if err != nil {
			return "", err
		}
		var matches []string
		err = filepath.WalkDir(workingDir, func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				if defaultSkipDirs[d.Name()] {
					return filepath.SkipDir
				}
				return nil
			}
			rel, err := filepath.Rel(workingDir, path)
			if err != nil {
				return nil
			}
			rel = filepath.ToSlash(rel)
			if matcher.Match(rel) {
				matches = append(matches, rel)
			}
			return nil
		})
		if err != nil {
			return "", err
		}
		sort.Strings(matches)
		if len(matches) == 0 {
			return "no matches", nil
		}
		total := len(matches)
		if total > maxSearchResults {
			matches = matches[:maxSearchResults]
			result := fmt.Sprintf("[showing %d of %d matches — results truncated]\n%s", maxSearchResults, total, strings.Join(matches, "\n"))
			return TruncateToolOutputHeadTail(result, maxToolResultBytes), nil
		}
		result := strings.Join(matches, "\n")
		return TruncateToolOutputHeadTail(result, maxToolResultBytes), nil
	}
}

func grepTool(workingDir string) func(ctx context.Context, rawArgs []byte) (string, error) {
	type args struct {
		Pattern string `json:"pattern"`
		Path    string `json:"path"`
	}
	return func(ctx context.Context, rawArgs []byte) (string, error) {
		// Block grep when the edit deadline is approaching and no edits have been made.
		if e := GetEditEnforcer(ctx); e != nil && e.ShouldBlockReads() {
			logging.InfoContext(ctx, "blocking Grep call — edit deadline approaching, no edits made yet")
			return "GREP BLOCKED — Edit deadline approaching with no edits. Call Edit or Write first.", nil
		}

		var payload args
		if err := json.Unmarshal(rawArgs, &payload); err != nil {
			return "", fmt.Errorf("invalid args: %w", err)
		}
		pattern := strings.TrimSpace(payload.Pattern)
		if pattern == "" {
			return "", fmt.Errorf("pattern is required")
		}
		pattern = sanitizeRegex(pattern)
		re, err := regexp.Compile(pattern)
		if err != nil {
			return "", fmt.Errorf("invalid regex: %w", err)
		}
		searchPath := payload.Path
		if strings.TrimSpace(searchPath) == "" {
			searchPath = "."
		}
		resolved, err := ResolvePath(workingDir, searchPath)
		if err != nil {
			return "", err
		}

		matches, err := grepSearchPath(workingDir, resolved, re)
		if err != nil {
			return "", err
		}

		if len(matches) == 0 {
			return "no matches", nil
		}
		total := len(matches)
		if total > maxSearchResults {
			matches = matches[:maxSearchResults]
			result := fmt.Sprintf("[showing %d of %d grep matches — results truncated]\n%s", maxSearchResults, total, strings.Join(matches, "\n"))
			return TruncateToolOutputHeadTail(result, maxToolResultBytes), nil
		}
		result := strings.Join(matches, "\n")
		return TruncateToolOutputHeadTail(result, maxToolResultBytes), nil
	}
}

func grepSearchPath(workingDir, resolved string, re *regexp.Regexp) ([]string, error) {
	var matches []string
	visit := grepVisitFile(workingDir, re, &matches)

	info, err := os.Stat(resolved)
	if err != nil {
		return nil, err
	}
	if info.IsDir() {
		if err := filepath.Walk(resolved, visit); err != nil {
			return nil, err
		}
	} else {
		if err := visit(resolved, info, nil); err != nil {
			return nil, err
		}
	}
	return matches, nil
}

func grepVisitFile(workingDir string, re *regexp.Regexp, matches *[]string) filepath.WalkFunc {
	return func(path string, info os.FileInfo, walkErr error) (retErr error) {
		if walkErr != nil {
			return walkErr
		}
		if info.IsDir() {
			if defaultSkipDirs[info.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		file, err := os.Open(path)
		if err != nil {
			return nil
		}
		defer func() {
			if cerr := file.Close(); cerr != nil && retErr == nil {
				retErr = cerr
			}
		}()
		rel, err := filepath.Rel(workingDir, path)
		if err != nil {
			rel = path
		}
		scanner := bufio.NewScanner(file)
		scanner.Buffer(make([]byte, 64*1024), maxToolOutput)
		lineNum := 1
		for scanner.Scan() {
			line := scanner.Text()
			if re.MatchString(line) {
				*matches = append(*matches, fmt.Sprintf("%s:%d:%s", filepath.ToSlash(rel), lineNum, line))
			}
			lineNum++
		}
		if err := scanner.Err(); err != nil {
			return err
		}
		return nil
	}
}

func bashTool(ex executor.Executor) func(ctx context.Context, rawArgs []byte) (string, error) {
	type args struct {
		Command string `json:"command"`
	}
	return func(ctx context.Context, rawArgs []byte) (string, error) {
		var payload args
		if err := json.Unmarshal(rawArgs, &payload); err != nil {
			return "", fmt.Errorf("invalid args: %w", err)
		}
		command := strings.TrimSpace(payload.Command)
		if command == "" {
			return "", fmt.Errorf("command is required")
		}

		if blocked, reason := IsBlockedCommand(command); blocked {
			return "", fmt.Errorf("%s", reason)
		}

		// Add executor metadata to the current span so traces show
		// what command ran and which executor backend handled it.
		span := trace.SpanFromContext(ctx)
		span.SetAttributes(
			attribute.String("squad.executor.type", ex.Type()),
			attribute.String("squad.tool.command", TruncateString(command, 1000)),
		)

		output, err := ex.Execute(ctx, command)
		if err != nil {
			return TruncateToolOutputHeadTail(string(limitOutput(output)), maxToolResultBytes), fmt.Errorf("command failed: %w", err)
		}
		return TruncateToolOutputHeadTail(string(limitOutput(output)), maxToolResultBytes), nil
	}
}

// tokenCalibrationKeyType is the context key for TokenCalibration.
type tokenCalibrationKeyType struct{}

// InitTokenCalibration attaches a TokenCalibration to the context.
func InitTokenCalibration(ctx context.Context) context.Context {
	return context.WithValue(ctx, tokenCalibrationKeyType{}, NewTokenCalibration())
}

// GetTokenCalibration retrieves the TokenCalibration from context, or nil.
func GetTokenCalibration(ctx context.Context) *TokenCalibration {
	if tc, ok := ctx.Value(tokenCalibrationKeyType{}).(*TokenCalibration); ok {
		return tc
	}
	return nil
}

func estimateTokens(messages []llms.MessageContent) int {
	total := 0
	for _, msg := range messages {
		for _, part := range msg.Parts {
			switch p := part.(type) {
			case llms.TextContent:
				total += len(p.Text) / 4
			case llms.ToolCallResponse:
				total += len(p.Content) / 4
			}
		}
	}
	return total
}

// estimateTokensCalibrated uses token calibration data if available.
func estimateTokensCalibrated(ctx context.Context, messages []llms.MessageContent) int {
	raw := estimateTokens(messages)
	if tc := GetTokenCalibration(ctx); tc != nil && tc.Samples() >= 2 {
		return tc.CalibratedEstimate(raw)
	}
	return raw
}

func compactMessages(ctx context.Context, messages []llms.MessageContent) []llms.MessageContent {
	tokens := estimateTokensCalibrated(ctx, messages)
	if tokens < contextTokenThreshold {
		return messages
	}

	protectedHead := 2
	if protectedHead > len(messages) {
		return messages
	}
	protectedTail := keepRecentMessages
	if protectedTail > len(messages)-protectedHead {
		protectedTail = len(messages) - protectedHead
	}
	compactEnd := len(messages) - protectedTail

	// Build a structured summary of what happened before compaction,
	// so the agent retains awareness of files read, patterns searched, etc.
	middleMessages := messages[protectedHead:compactEnd]
	summary := CompactionSummary(middleMessages)

	compacted := make([]llms.MessageContent, len(messages))
	copy(compacted, messages)

	for i := protectedHead; i < compactEnd; i++ {
		if compacted[i].Role != llms.ChatMessageTypeTool {
			continue
		}
		newParts := make([]llms.ContentPart, len(compacted[i].Parts))
		for j, part := range compacted[i].Parts {
			if resp, ok := part.(llms.ToolCallResponse); ok {
				origLen := len(resp.Content)
				if origLen > 200 {
					resp.Content = fmt.Sprintf("[tool output compacted — was %d bytes]", origLen)
				}
				newParts[j] = resp
			} else {
				newParts[j] = part
			}
		}
		compacted[i].Parts = newParts
	}

	// Inject the session state summary as a system message right after the
	// protected head, so the agent knows what it has already done.
	if summary != "" {
		summaryMsg := llms.MessageContent{
			Role:  llms.ChatMessageTypeHuman,
			Parts: []llms.ContentPart{llms.TextPart(summary)},
		}
		// Insert after protected head messages.
		result := make([]llms.MessageContent, 0, len(compacted)+1)
		result = append(result, compacted[:protectedHead]...)
		result = append(result, summaryMsg)
		result = append(result, compacted[protectedHead:]...)
		compacted = result
	}

	after := estimateTokens(compacted)
	logging.InfoContext(ctx, "compacted context: ~%d tokens -> ~%d tokens", tokens, after)
	return compacted
}

func TruncateToolOutputHeadTail(output string, maxBytes int) string {
	if len(output) <= maxBytes {
		return output
	}

	headSize := maxBytes * 3 / 4
	tailSize := maxBytes - headSize

	head := output[:headSize]
	tail := output[len(output)-tailSize:]

	// Snap to line boundaries
	headEnd := strings.LastIndex(head, "\n")
	if headEnd < 0 {
		headEnd = len(head)
	}
	tailStart := strings.Index(tail, "\n")
	if tailStart < 0 {
		tailStart = 0
	} else {
		tailStart++
	}

	totalLines := strings.Count(output, "\n") + 1
	headLines := strings.Count(head[:headEnd], "\n") + 1
	tailLines := strings.Count(tail[tailStart:], "\n") + 1
	omitted := totalLines - headLines - tailLines
	if omitted < 0 {
		omitted = 0
	}

	return fmt.Sprintf("%s\n\n... [%d lines omitted from tool output — total %d bytes] ...\n\n%s",
		head[:headEnd], omitted, len(output), tail[tailStart:])
}

// FlexBool unmarshals both JSON booleans and string representations
// ("true"/"false") that LLMs sometimes produce for boolean fields.
type FlexBool bool

func (b *FlexBool) UnmarshalJSON(data []byte) error {
	var v bool
	if err := json.Unmarshal(data, &v); err == nil {
		*b = FlexBool(v)
		return nil
	}
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("replace_all must be bool or string, got %s", string(data))
	}
	switch strings.ToLower(strings.TrimSpace(s)) {
	case "true", "1", "yes":
		*b = true
	default:
		*b = false
	}
	return nil
}

func ResolvePath(workingDir, input string) (string, error) {
	if strings.TrimSpace(input) == "" {
		return "", fmt.Errorf("path is required")
	}
	var joined string
	if filepath.IsAbs(input) {
		joined = filepath.Clean(input)
	} else {
		joined = filepath.Join(workingDir, input)
	}
	abs, err := filepath.Abs(joined)
	if err != nil {
		return "", err
	}
	wd, err := filepath.Abs(workingDir)
	if err != nil {
		return "", err
	}
	if abs != wd && !strings.HasPrefix(abs, wd+string(filepath.Separator)) {
		return "", fmt.Errorf("path %q is outside working directory", input)
	}
	return abs, nil
}

func limitOutput(data []byte) []byte {
	if len(data) <= maxToolOutput {
		return data
	}
	head := data[:maxToolOutput]
	return append(head, []byte("\n...output truncated\n")...)
}

type globMatcher struct {
	re *regexp.Regexp
}

func newGlobMatcher(pattern string) (*globMatcher, error) {
	normalized := filepath.ToSlash(pattern)
	regex, err := globToRegex(normalized)
	if err != nil {
		return nil, err
	}
	re, err := regexp.Compile(regex)
	if err != nil {
		return nil, err
	}
	return &globMatcher{re: re}, nil
}

func (g *globMatcher) Match(path string) bool {
	return g.re.MatchString(path)
}

func globToRegex(pattern string) (string, error) {
	var buf strings.Builder
	buf.WriteString("^")
	runes := []rune(pattern)
	for i := 0; i < len(runes); i++ {
		ch := runes[i]
		if ch == '*' {
			if i+1 < len(runes) && runes[i+1] == '*' {
				buf.WriteString(".*")
				i++
			} else {
				buf.WriteString(`[^/]*`)
			}
			continue
		}
		if ch == '?' {
			buf.WriteString(".")
			continue
		}
		if strings.ContainsRune(`.+()|[]{}^$\\`, ch) {
			buf.WriteString(`\`)
		}
		buf.WriteRune(ch)
	}
	buf.WriteString("$")
	return buf.String(), nil
}

func TruncateString(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
