---
name: 🚨 Semgrep Analysis
on:
  merge_group:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  schedule:
    # Run once a week (see https://crontab.guru)
    - cron: "0 0 * * 0"
  workflow_dispatch:

# Cancel any in-progress job when a new workflow is triggered
concurrency:
  cancel-in-progress: true
  group: pre-commit-${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  semgrep:
    name: 🚨 Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.168.0

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Run Semgrep analysis
        run: |
          semgrep scan --error \
            --config p/security-audit \
            --config p/secrets \
            --config p/ci \
            --config p/supply-chain \
            --config p/golang
